kind: pipeline
name: default

steps:
  - name: build-test-web
    image: gradle:6.0-jdk8
    commands:
      - gradle build webProdAssemble --stacktrace
  - name: upload
    image: appleboy/drone-scp
    settings:
      host:
        - bandbox.dreamhost.com
      username:
        from_secret: BANDBOX_FTP_USERNAME
      password:
        from_secret: BANDBOX_FTP_PASSWORD
      port: 22
      command_timeout: 4m
      rm: true
      target: ~/demos.acornui.com/
      source:
        - ./**/build/wwwProd

---
kind: pipeline
name: jdk11

steps:
  - name: build-test-web
    image: gradle:5.5-jdk11
    commands:
      - gradle build webProdAssemble --stacktrace